## Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

### Решение:

In [2]:
import numpy as np

In [10]:
number = int(input("Input the number: "))
a = np.arange(number,-1,-1)
a

Input the number: 15


array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

### Решение 1:

In [19]:
N = int(input("Введите число N:"))
matrix = np.diag(np.arange(N, -1, -1))
print("Матрица: \n", matrix)
print("Сумма элементов диагональной матрицы: ", sum(range(N, -1, -1)))

Введите число N:8
Матрица: 
 [[8 0 0 0 0 0 0 0 0]
 [0 7 0 0 0 0 0 0 0]
 [0 0 6 0 0 0 0 0 0]
 [0 0 0 5 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0]]
Сумма элементов диагональной матрицы:  36


### Решение 2:

In [18]:
N_1 = int(input("Введите число N: "))
matrix_1 = np.diag(np.arange(N_1,-1,-1))
print("Матрица: \n", matrix_1)
sum_of_matrix_diagonal = sum(matrix_1[i][i] for i in range(N_1))
    
print("Сумма элементов диагональной матрицы: ", sum_of_matrix_diagonal)

Введите число N: 5
Матрица: 
 [[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]
Сумма элементов диагональной матрицы:  15


## Задание 3

Решите систему уравнений:  
4x + 2y + z = 4  
x + 3y = 12  
5y + 4z = -3  

### Решение:

In [15]:
from numpy import linalg
array_of_factors = np.array([
    [4,2,1], 
    [1,3,0], 
    [0, 5, 4]
])
array_of_results = np.array([4, 12, -3])
array_of_variables = linalg.solve(array_of_factors, array_of_results)
print("Решение: ", array_of_variables)
print ("Результат проверки решения: ", np.allclose( np.dot(array_of_factors, array_of_variables),array_of_results ))

Решение:  [ 0.46666667  3.84444444 -5.55555556]
Результат проверки решения:  True


## Задание 4

Имеется матрица users_stats для покупок пользователей в интернет-магазине. Индекс строки в матрице - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем. Матрица в виде numpy array. 

На сайт заходит очередной посетитель, со следующим списком покупок: [0, 1, 2, 0, 0, 0]

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

### Решение:

In [3]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
users_stats

array([[2, 1, 0, 0, 0, 0],
       [1, 1, 2, 1, 0, 0],
       [2, 0, 1, 0, 0, 0],
       [1, 1, 2, 1, 0, 1],
       [0, 0, 1, 2, 0, 0],
       [0, 0, 0, 0, 0, 5],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 3],
       [1, 0, 0, 2, 1, 4]])

In [21]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
next_user_stats_len = np.linalg.norm(next_user_stats)
min_cos = np.array([])
for i in users_stats:
    i_len = np.linalg.norm(i)
    cos_i_next = np.dot(i,next_user_stats)/(next_user_stats_len * i_len)
    angle = np.arccos(cos_i_next)
    min_cos = np.append(min_cos, angle)
result = np.argmin(min_cos)
print("Номер строки для пользователя с максимально похожим списком покупок: ", result+1)

Номер строки для пользователя с максимально похожим списком покупок:  8
